#spring:
#  security:
#    user:
#      name: user
#      password: user
##  main:
##    allow-bean-definition-overriding: true

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html


## 关闭thymeleaf缓存 开发时使用 生产不要使用
#  spring.thymeleaf.cache=false
#  ## 检查模板是否存在，然后再呈现
#  spring.thymeleaf.check-template-location=true
#  #Content-Type值
#  spring.thymeleaf.servlet.content-type=text/html
#  #启用MVC Thymeleaf视图分辨率
#  spring.thymeleaf.enabled=true
#  #模板编码
#  spring.thymeleaf.mode=LEGACYHTML5
#  # 在构建URL时预先查看名称的前缀
#  spring.thymeleaf.prefix=classpath:/templates/
#  # 构建URL时附加查看名称的后缀.
#  spring.thymeleaf.suffix=.html
## 链中模板解析器的顺序
##spring.thymeleaf.template-resolver-order= o
